apiVersion: v1
kind: Service
metadata:
  name: service-customer
  labels:
    name: service-customer
    app: fintech-app
    version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    name: service-customer
    app: fintech-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-customer
  labels:
    name: service-customer
    app: fintech-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: service-customer
      app: fintech-app
      version: v1
  template:
    metadata:
      labels:
        name: service-customer
        app: fintech-app
        version: v1
    spec:
      containers:
        - name: interop
          image: 730880032795.dkr.ecr.eu-west-1.amazonaws.com/service-customer:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "PORT"
              value: "80"
            - name: "AUTHENTICATION_SERVICE_URL"
              value: "http://service-auth-v1.default.svc.cluster.local/authenticate"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets:
        - name: awsecr-cred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-customer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: fintech.demo.local
    http:
      paths:
      - path: /customer/v1(/|$)(.*)
        backend:
          serviceName: service-customer
          servicePort: 80