apiVersion: v1
kind: Service
metadata:
  name: service-payments
  labels:
    name: service-payments
    app: fintech-app
    version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    name: service-payments
    app: fintech-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-payments
  labels:
    name: service-payments
    app: fintech-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: service-payments
      app: fintech-app
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        name: service-payments
        app: fintech-app
        version: v1
    spec:
      containers:
        - name: interop
          image: 730880032795.dkr.ecr.eu-west-1.amazonaws.com/service-payments:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "PORT"
              value: "80"
            - name: "CUSTOMER_SERVICE_LOGIN_URL"
              value: "http://service-customer.default.svc.cluster.local/login"
            - name: "MOCKY_EXTERNAL_URL"
              value: "http://www.mocky.io/v2/5db852283b0000eda535f04e"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets:
        - name: awsecr-cred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-payments-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: fintech.demo.local
    http:
      paths:
      - path: /payments/v1(/|$)(.*)
        backend:
          serviceName: service-payments
          servicePort: 80