apiVersion: v1
kind: Service
metadata:
  name: service-customer-deployment
  labels:
    name: service-customer-deployment
    app: service-customer-deployment
    version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    name: service-customer-deployment
    app: service-customer-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-customer-deployment
  labels:
    name: service-customer-deployment
    app: service-customer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: service-customer-deployment
      app: service-customer-deployment
      version: v1
  template:
    metadata:
      labels:
        name: service-customer-deployment
        app: service-customer-deployment
        version: v1
    spec:
      containers:
        - name: interop
          image: cloud.canister.io:5000/interop/service-customer:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "PORT"
              value: "80"
            - name: "AUTHENTICATION_SERVICE_URL"
              value: "http://http.TCP.service-auth-deployment.default.svc.cluster.local/authenticate"
      imagePullSecrets:
        - name: canister.io
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-customer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: fintech.demo.local
    http:
      paths:
      - path: /customer/v1(/|$)(.*)
        backend:
          serviceName: service-customer-deployment
          servicePort: 80