apiVersion: v1
kind: Service
metadata:
  name: service-auth
  labels:
    name: service-auth
    app: fintech-app
    version: v2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    name: service-auth
    app: fintech-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  labels:
    name: service-auth
    app: fintech-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: service-auth
      app: fintech-app
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        name: service-auth
        app: fintech-app
        version: v2
    spec:
      containers:
        - name: interop
          image: cloud.canister.io:5000/interop/service-auth:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "PORT"
              value: "80"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets:
        - name: canister.io
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: fintech.demo.local
    http:
      paths:
      - path: /auth/v2(/|$)(.*)
        backend:
          serviceName: service-auth
          servicePort: 80